apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{app_name}}
  template:
    metadata:
      labels:
        app: {{app_name}}
    spec:
      containers:
        - name: {{app_name}}
          image: {{backend_image}}
          env:
            - name: REDIS_ENABLED
              value: "false"
          ports:
            - containerPort: 8080 