apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: {{namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{app_name}}
  template:
    metadata:
      labels:
        app: {{app_name}}
    spec:
      containers:
        - name: {{app_name}}
          image: {{frontend_image}}
          ports:
            - containerPort: 80