apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{prNumber}}
  namespace: {{namespace}}
spec:
  rules:
    - host: preview.local
      http:
        paths:
          -path: /pr-{{prNumber}}
          pathType: Prefix
          backend:
            service:
            name: service-{{prNumber}}
            port:
              number: 80