apiVersion: v1
kind: Service
metadata:
  name: {{service_name}}
  namespace: {{namespace}}
spec:
  type: NodePort
  selector:
    app: {{app_name}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{nodePort}}
